-- we don't know how to generate root <with-no-name> (class Root) :(

comment on database postgres is 'default administrative connection database';

create sequence kinoprojekt.isekohad_id_seq;

alter sequence kinoprojekt.isekohad_id_seq owner to "Admin";

create sequence public.kinoprojekt;

alter sequence public.kinoprojekt owner to "Admin";

create table kinoprojekt."user"
(
    id            bigint generated always as identity
        constraint user_pk
            primary key,
    "user"        varchar(255)  not null,
    first_name    varchar(1024) not null,
    last_name     varchar(1024) not null,
    phone_number  numeric(128)  not null,
    email         varchar(1024) not null,
    date_of_birth date,
    password_hash text          not null
);

alter table kinoprojekt."user"
    owner to "Admin";

create table kinoprojekt.kino
(
    id             bigint generated by default as identity
        constraint kino_pk
            primary key,
    kino_nimi      varchar(255) not null,
    tänava_aadress varchar(255) not null,
    linn           varchar(255) not null,
    postiindeks    varchar(32)  not null,
    riik           varchar(255) not null
);

alter table kinoprojekt.kino
    owner to "Admin";

create table kinoprojekt.kinosaalid
(
    id           bigint generated by default as identity
        constraint kinosaalid_pk
            primary key,
    kino_id      bigint                                      not null
        constraint kinosaalid_kino_id_fk
            references kinoprojekt.kino
            on delete restrict,
    name         varchar(50)                                 not null,
    ekraani_tüüp varchar(20) default '2D'::character varying not null,
    mahutavus    smallint                                    not null
);

alter table kinoprojekt.kinosaalid
    owner to "Admin";

create table kinoprojekt.istekohad
(
    id       integer generated by default as identity
        constraint id
            primary key
        constraint koridor_id
            references kinoprojekt.kinosaalid,
    rida     varchar(3) not null
        constraint istekohad_pk
            unique,
    istekoht smallint   not null
);

alter table kinoprojekt.istekohad
    owner to "Admin";

alter sequence kinoprojekt.isekohad_id_seq owned by kinoprojekt.istekohad.id;

create unique index istekohad_rida_uindex
    on kinoprojekt.istekohad (rida);

create table kinoprojekt.filmid
(
    id                integer generated by default as identity
        constraint filmid_id
            primary key,
    pealkiri          varchar(255) default ''::character varying not null,
    kirjeldus         text,
    filmi_pikkus      smallint     default 0                     not null,
    väljalaskekuupäev date,
    vanusepiirang     varchar(10),
    keel              varchar(50),
    plakati_url       varchar(500),
    treileri_url      varchar(500),
    väikeväärtus      boolean      default false                 not null
);

alter table kinoprojekt.filmid
    owner to "Admin";

create table kinoprojekt.žanrid
(
    id   integer generated by default as identity
        constraint žanrid_id
            primary key,
    nimi varchar(50) not null
);

alter table kinoprojekt.žanrid
    owner to "Admin";

create unique index žanrid_id_nimi_uindex
    on kinoprojekt.žanrid (id, nimi);

create table kinoprojekt.seansid
(
    id         integer generated by default as identity
        primary key,
    filmi_id   integer       not null
        references kinoprojekt.filmid,
    saali_id   integer       not null
        references kinoprojekt.kinosaalid,
    algus_aeg  timestamp     not null,
    lopu_aeg   timestamp     not null,
    keel       varchar(50),
    subtiitrid varchar(50),
    alghind    numeric(8, 2) not null,
    constraint seansid_check
        check (lopu_aeg > algus_aeg)
);

alter table kinoprojekt.seansid
    owner to "Admin";

create table kinoprojekt.broneeringud
(
    id          integer generated by default as identity
        primary key,
    kasutaja_id integer                                        not null
        references kinoprojekt."user",
    seansi_id   integer                                        not null
        references kinoprojekt.seansid,
    staatus     varchar(20) default 'ootel'::character varying not null,
    kogusumma   numeric(8, 2)                                  not null,
    loodud      timestamp   default CURRENT_TIMESTAMP
);

alter table kinoprojekt.broneeringud
    owner to "Admin";

create table kinoprojekt.broneeritud_kohad
(
    id             integer generated by default as identity
        primary key,
    broneeringu_id integer       not null
        references kinoprojekt.broneeringud,
    seansi_id      integer       not null
        references kinoprojekt.seansid,
    istekoha_id    integer       not null
        references kinoprojekt.istekohad,
    hind           numeric(8, 2) not null,
    unique (seansi_id, istekoha_id)
);

alter table kinoprojekt.broneeritud_kohad
    owner to "Admin";

create table kinoprojekt.maksed
(
    id             integer generated by default as identity
        primary key,
    broneeringu_id integer       not null
        references kinoprojekt.broneeringud,
    summa          numeric(8, 2) not null,
    makseviis      varchar(30)   not null,
    staatus        varchar(20)   not null,
    makse_viide    varchar(255),
    makstud        timestamp
);

alter table kinoprojekt.maksed
    owner to "Admin";

create table kinoprojekt.arvustused
(
    id          integer generated by default as identity
        primary key,
    kasutaja_id integer not null
        references kinoprojekt."user",
    filmi_id    integer not null
        references kinoprojekt.filmid,
    hinnang     smallint
        constraint arvustused_hinnang_check
            check ((hinnang >= 1) AND (hinnang <= 5)),
    kommentaar  text,
    loodud      timestamp default CURRENT_TIMESTAMP
);

alter table kinoprojekt.arvustused
    owner to "Admin";

