-- we don't know how to generate root <with-no-name> (class Root) :(

comment on database postgres is 'default administrative connection database';

create sequence kinoprojekt.isekohad_id_seq;

alter sequence kinoprojekt.isekohad_id_seq owner to "Admin";

create sequence public.kinoprojekt;

alter sequence public.kinoprojekt owner to "Admin";

create table kinoprojekt."user"
(
    id            bigint generated always as identity
        constraint user_pk
            primary key,
    "user"        varchar(255)  not null,
    first_name    varchar(1024) not null,
    last_name     varchar(1024) not null,
    phone_number  numeric(128)  not null,
    email         varchar(1024) not null,
    date_of_birth date,
    password_hash text          not null
);

alter table kinoprojekt."user"
    owner to "Admin";

create table kinoprojekt.kino
(
    id             bigint generated by default as identity
        constraint kino_pk
            primary key,
    kino_nimi      varchar(255) not null,
    tänava_aadress varchar(255) not null,
    linn           varchar(255) not null,
    postiindeks    varchar(32)  not null,
    riik           varchar(255) not null
);

alter table kinoprojekt.kino
    owner to "Admin";

create table kinoprojekt.kinosaalid
(
    id           bigint generated by default as identity
        constraint kinosaalid_pk
            primary key,
    kino_id      bigint                                      not null
        constraint kinosaalid_kino_id_fk
            references kinoprojekt.kino
            on delete restrict,
    name         varchar(50)                                 not null,
    ekraani_tüüp varchar(20) default '2D'::character varying not null,
    mahutavus    smallint                                    not null
);

alter table kinoprojekt.kinosaalid
    owner to "Admin";

create table kinoprojekt.istekohad
(
    id       integer generated by default as identity
        constraint id
            primary key
        constraint koridor_id
            references kinoprojekt.kinosaalid,
    rida     varchar(3) not null
        constraint istekohad_pk
            unique,
    istekoht smallint   not null
);

alter table kinoprojekt.istekohad
    owner to "Admin";

alter sequence kinoprojekt.isekohad_id_seq owned by kinoprojekt.istekohad.id;

